config:
  DATABASE_URL: jdbc:postgresql://localhost:${config.DATABASE_PORT}/${config.DATABASE_NAME}
  DATABASE_USERNAME: admin
  DATABASE_PASSWORD: test
  DATABASE_PORT: 5434
  DATABASE_PORT_VACATION: 5436
  DATABASE_NAME: vacation-db
  ACCOUNTING_SERVICE_NAME: accounting-service
  RESOURCES_SERVICE_NAME: resources-service
  ACCOUNTING_BASE_URL: http://localhost:8100
  RESOURCE_BASE_URL: http://localhost:8099
  EUREKA_DEFAULT_ZONE: http://localhost:8761/eureka
